# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 22:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=250)),
                ('video_desc', models.CharField(max_length=250)),
                ('video_file', models.FileField(upload_to='')),
            ],
        ),
    ]
