# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-20 13:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20171220_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_desc',
            field=models.CharField(default='Galatec', max_length=250),
            preserve_default=False,
        ),
    ]
