# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 10:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_category_category_desc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name': 'category', 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('-created',)},
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_desc',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_logo',
        ),
        migrations.RemoveField(
            model_name='category',
            name='category_name',
        ),
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, default='demo data', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='demo-data', max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='products',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to='products/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(db_index=True, default='demo data', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='slug',
            field=models.SlugField(default='demo-data', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='stock',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='products',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.Category'),
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_count',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_description',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='product_price',
        ),
        migrations.AlterIndexTogether(
            name='products',
            index_together=set([('id', 'slug')]),
        ),
    ]
