# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-12 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='0722000000', max_length=50),
            preserve_default=False,
        ),
    ]
